"""Execute NXOpen journals through NX's own `run_journal` launcher.

This replaces the original `nx_bridge.ps1`. Running a journal is deliberately
kept separate from the *live* bridge: `run_journal` starts its own NX process
and does **not** attach to an already-open session, so it is the right tool for
batch/file work and the wrong tool for changing the part a user is looking at.

The environment handed to `run_journal` is built explicitly rather than
inherited, so a machine with stale `UGII_*` variables pointing at a different
release cannot silently redirect the run.
"""

from __future__ import annotations

import os
import re
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Mapping, Sequence

from .config import Settings
from .contracts import InvalidArgument, JournalFailed, SkillError
from .discovery import NxInstall

DEFAULT_JOURNAL_TIMEOUT = 3600

# ---------------------------------------------------------------------------
# Journal source templates
# ---------------------------------------------------------------------------

CREATE_PART_JOURNAL = '''"""Generated by nx-skill: create and display a new modelling part."""

import NXOpen


def main():
    session = NXOpen.Session.GetSession()
    session.ApplicationSwitchImmediate("UG_APP_MODELING")
    part = session.Parts.NewDisplay(__PART__, NXOpen.Part.Units.Millimeters)
    session.Parts.SetWork(part)
    session.Parts.SetDisplay(part, False, False)
    part.ModelingViews.WorkView.Fit()
    part.Save(
        NXOpen.BasePart.SaveComponents.TrueValue,
        NXOpen.BasePart.CloseAfterSave.FalseValue,
    )
    session.ListingWindow.Open()
    session.ListingWindow.WriteLine("Created part: " + part.FullPath)


if __name__ == "__main__":
    main()
'''

OPEN_PART_JOURNAL = '''"""Generated by nx-skill: open and display an existing part."""

import NXOpen


def main():
    session = NXOpen.Session.GetSession()
    session.ApplicationSwitchImmediate("UG_APP_MODELING")
    part, load_status = session.Parts.OpenBaseDisplay(__PART__)
    session.Parts.SetWork(part)
    session.Parts.SetDisplay(part, False, False)
    part.ModelingViews.WorkView.Fit()
    try:
        load_status.Dispose()
    except Exception:
        pass
    session.ListingWindow.Open()
    session.ListingWindow.WriteLine("Opened part: " + part.FullPath)


if __name__ == "__main__":
    main()
'''

_JOURNAL_FILENAME = re.compile(r"^[A-Za-z0-9._-]+\.py$")


def _python_literal(value: str) -> str:
    """Render *value* as a Python string literal safe for a generated journal."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


@dataclass(frozen=True)
class JournalResult:
    journal: Path
    returncode: int
    stdout: str
    stderr: str
    duration_seconds: float

    @property
    def ok(self) -> bool:
        return self.returncode == 0

    def to_dict(self) -> dict[str, object]:
        return {
            "journal": str(self.journal),
            "returncode": self.returncode,
            "durationSeconds": round(self.duration_seconds, 3),
            "stdout": self.stdout[-8000:],
            "stderr": self.stderr[-8000:],
        }


class JournalRunner:
    """Runs NXOpen journals in a fresh, non-interactive NX process."""

    def __init__(self, install: NxInstall, settings: Settings) -> None:
        self.install = install
        self.settings = settings

    # -- environment ------------------------------------------------------
    def environment(self, *, load_runtime: bool = False) -> dict[str, str]:
        """Build the environment `run_journal` needs, overriding stale values."""
        env = os.environ.copy()
        nxbin = self.install.nxbin
        env["UGII_BASE_DIR"] = str(self.install.root)
        env["UGII_ROOT_DIR"] = str(nxbin)
        # Batch journals deliberately do NOT load this package's custom directory:
        # doing so would make a headless run start the interactive live-bridge
        # listener. Only an interactive launch passes load_runtime=True.
        if load_runtime:
            env["UGII_CUSTOM_DIRECTORY_FILE"] = str(self.ensure_custom_directory_file())
        env["NX_SKILL_NX_ROOT"] = str(self.install.root)
        env["NX_SKILL_WORKSPACE"] = str(self.settings.ensure_workspace())

        parts = [p for p in env.get("PATH", "").split(os.pathsep) if p]
        if not any(p.rstrip("\\/").casefold() == str(nxbin).rstrip("\\/").casefold() for p in parts):
            env["PATH"] = str(nxbin) + os.pathsep + env.get("PATH", "")
        return env

    def ensure_custom_directory_file(self) -> Path:
        """Generate `custom_dirs.dat` pointing at *this* package's nx_runtime.

        The file is generated per user rather than committed, because the answer
        contains an absolute path that is different on every machine.
        """
        target = self.settings.custom_directory_file()
        target.parent.mkdir(parents=True, exist_ok=True)
        content = (
            "# Generated by nx-skill. Do not edit by hand.\n"
            "# Points Siemens NX at this package's custom runtime directory.\n"
            f"{self.settings.runtime_root()}\n"
        )
        try:
            if not target.exists() or target.read_text(encoding="utf-8", errors="replace") != content:
                target.write_text(content, encoding="utf-8")
        except OSError as exc:
            raise SkillError(
                f"Could not write the NX custom directory file at {target}: {exc}",
                suggestion="Check permissions on the configuration directory, or set NX_SKILL_* to a writable location.",
            ) from exc
        return target

    # -- execution --------------------------------------------------------
    def run(
        self,
        journal: str | Path,
        args: Sequence[str] = (),
        *,
        timeout: int = DEFAULT_JOURNAL_TIMEOUT,
    ) -> JournalResult:
        """Run one journal file and return its captured output."""
        # Journals are confined to the workspace on purpose: an agent must not be
        # able to talk this package into executing an arbitrary file elsewhere on
        # the machine, and it keeps generated and reviewed journals together.
        path = self._confine(journal, what="journal")
        if not path.is_file():
            raise InvalidArgument(
                f"Journal not found: {path}",
                suggestion="Pass a path to an existing .py NXOpen journal, relative to the workspace.",
            )

        runner = self.install.run_journal
        if not runner.exists():
            raise JournalFailed(
                f"run_journal was not found at {runner}.",
                suggestion="The installation does not look complete; check NX_SKILL_NX_ROOT.",
            )

        command: list[str] = [str(runner), "-nx", str(path)]
        if args:
            command.append("-args")
            command.extend(str(a) for a in args)

        started = time.monotonic()
        try:
            completed = subprocess.run(
                command,
                cwd=str(path.parent),
                env=self.environment(load_runtime=False),
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                timeout=timeout,
            )
        except subprocess.TimeoutExpired as exc:
            raise SkillError(
                f"The NX journal did not finish within {timeout} seconds.",
                code="NX_JOURNAL_TIMEOUT",
                suggestion="The journal may still be running inside NX; verify the part state before retrying.",
                details={"journal": str(path)},
            ) from exc
        except OSError as exc:
            raise JournalFailed(f"Could not start run_journal: {exc}") from exc

        result = JournalResult(
            journal=path,
            returncode=completed.returncode,
            stdout=completed.stdout or "",
            stderr=completed.stderr or "",
            duration_seconds=time.monotonic() - started,
        )
        if not result.ok:
            raise JournalFailed(
                f"run_journal exited with code {result.returncode}.",
                suggestion="Read the journal output for the NXOpen error; the part may be partially modified.",
                details=result.to_dict(),
            )
        return result

    # -- generated journals ----------------------------------------------
    def write_journal(self, name: str, source: str) -> Path:
        """Write generated journal source into the workspace and return its path."""
        if not _JOURNAL_FILENAME.match(name):
            raise InvalidArgument(
                f"Unsafe journal name: {name!r}",
                suggestion="Use a simple file name such as 'create_part.py'.",
            )
        target = self.settings.generated_root() / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(source, encoding="utf-8")
        return target

    def create_part(self, part_path: str | Path, *, timeout: int = DEFAULT_JOURNAL_TIMEOUT) -> JournalResult:
        """Create a new part, rendered from :data:`CREATE_PART_JOURNAL`."""
        return self._run_rendered("create_part.py", CREATE_PART_JOURNAL, part_path, timeout=timeout)

    def open_part(self, part_path: str | Path, *, timeout: int = DEFAULT_JOURNAL_TIMEOUT) -> JournalResult:
        """Open an existing part, rendered from :data:`OPEN_PART_JOURNAL`."""
        return self._run_rendered("open_part.py", OPEN_PART_JOURNAL, part_path, timeout=timeout)

    def _confine(self, candidate: str | Path, *, what: str) -> Path:
        """Resolve *candidate* strictly inside the workspace.

        Absolute paths pointing outside the workspace are rejected rather than
        accepted, because "the caller passed an absolute path" is not a reason to
        let file operations escape the configured boundary.
        """
        from .contracts import Workspace

        workspace = Workspace(self.settings.ensure_workspace())
        text = str(candidate)
        if Path(text).is_absolute():
            resolved = workspace.ensure_inside(text)
            return resolved
        if what == "journal":
            return workspace.resolve(text)
        return workspace.resolve(text)

    def _run_rendered(self, name: str, template: str, part_path: str | Path, *, timeout: int) -> JournalResult:
        target = self._confine(part_path, what="part")
        if name == "open_part.py" and not target.is_file():
            raise InvalidArgument(f"No such part to open: {target}")
        target.parent.mkdir(parents=True, exist_ok=True)
        source = template.replace("__PART__", _python_literal(str(target)))
        journal = self.write_journal(name, source)
        try:
            return self.run(journal, timeout=timeout)
        finally:
            if self.settings.delete_generated:
                try:
                    journal.unlink()
                except OSError:
                    pass
