"""Install this package as an NX custom directory.

NX finds menus, dialogs and startup scripts through
`UGII_CUSTOM_DIRECTORY_FILE`, which points at a file listing custom root
directories. The review dialog and the `NX Skill` menu live in this package's
`nx_runtime`, so unless NX is told about it, the menu simply is not there.

Two ways to get that done:

* **Launch NX through this package** (`nx-skill live status` with auto-launch, or
  `LiveBridge.launch_gui`), which sets the variable for that process only. Nothing
  is written to the user's environment.
* **Install the loader** (this module), which writes the variable at user scope so
  an NX started from the Start Menu also picks it up.

Installing is opt-in and reversible: it writes exactly one user environment
variable and one file under the user's own config directory, and touching neither
the NX installation nor the machine-wide environment.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Any, Iterable

from .config import Settings
from .contracts import SkillError

ENV_NAME = "UGII_CUSTOM_DIRECTORY_FILE"


def _roots_in_custom_directory_file(path: Path) -> list[str]:
    """Read the non-comment lines of a custom_dirs.dat: the roots NX will load."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []
    roots: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            roots.append(stripped)
    return roots


def preserved_roots(settings: Settings, target: Path | None = None) -> list[str]:
    """Roots another NX customisation registered, which we must not silently drop.

    \"UGII_CUSTOM_DIRECTORY_FILE\" holds one path, so installing this package
    normally *replaces* whatever was configured before -- breaking every other NX
    customisation on the machine, including the one that produced the review
    workflow's ancestors. A custom_dirs.dat is a *list* of roots, so the previous
    registration can simply be carried over.
    """
    target = target or settings.custom_directory_file()
    current = _read_user_env(ENV_NAME)
    if not current:
        return []
    current_path = Path(current)
    if current_path == target or not current_path.is_file():
        return []

    ours = str(settings.runtime_root())
    kept: list[str] = []
    for root in _roots_in_custom_directory_file(current_path):
        if root == ours or root in kept:
            continue
        kept.append(root)
    return kept


def custom_directory_content(settings: Settings, extra_roots: Iterable[str] = ()) -> str:
    """The body of the file NX reads: this package's runtime, plus preserved roots."""
    lines = [
        "# Generated by nx-skill. Do not edit by hand.",
        "# Points Siemens NX at this package's custom runtime directory.",
        str(settings.runtime_root()),
    ]
    extras = [root for root in extra_roots if root and root != str(settings.runtime_root())]
    if extras:
        lines.append("")
        lines.append("# Carried over from the previously configured custom directory file so that")
        lines.append("# other NX customisations on this machine keep working:")
        lines.extend(extras)
    return "\n".join(lines) + "\n"


def write_custom_directory_file(settings: Settings, extra_roots: Iterable[str] | None = None) -> Path:
    target = settings.custom_directory_file()
    target.parent.mkdir(parents=True, exist_ok=True)
    if extra_roots is None:
        extra_roots = preserved_roots(settings, target)
    content = custom_directory_content(settings, extra_roots)
    try:
        if not target.exists() or target.read_text(encoding="utf-8", errors="replace") != content:
            target.write_text(content, encoding="utf-8")
    except OSError as exc:
        raise SkillError(
            f"Could not write {target}: {exc}",
            code="LOADER_WRITE_FAILED",
            suggestion="Check permissions on the configuration directory.",
        ) from exc
    return target


def _read_user_env(name: str) -> str | None:
    if sys.platform != "win32":
        return os.environ.get(name)
    try:
        import winreg
    except ImportError:
        return None
    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment") as key:
            value, _kind = winreg.QueryValueEx(key, name)
            return str(value)
    except OSError:
        return None


def _write_user_env(name: str, value: str | None) -> bool:
    """Set or delete a user-scope environment variable. Returns success."""
    if sys.platform != "win32":
        return False
    try:
        import winreg
    except ImportError:
        return False
    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment", 0, winreg.KEY_SET_VALUE) as key:
            if value is None:
                try:
                    winreg.DeleteValue(key, name)
                except FileNotFoundError:
                    pass
            else:
                winreg.SetValueEx(key, name, 0, winreg.REG_SZ, value)
        _broadcast_environment_change()
        return True
    except OSError:
        return False


def _broadcast_environment_change() -> None:
    """Tell running processes the user environment changed.

    Without this, an already-open Explorer keeps handing NX the old environment and
    the user concludes the install did nothing. It is best-effort: the setting is
    correct either way, and a new logon always picks it up.
    """
    try:
        import ctypes

        HWND_BROADCAST = 0xFFFF
        WM_SETTINGCHANGE = 0x001A
        SMTO_ABORTIFHUNG = 0x0002
        result = ctypes.c_long()
        ctypes.windll.user32.SendMessageTimeoutW(  # type: ignore[attr-defined]
            HWND_BROADCAST, WM_SETTINGCHANGE, 0, ctypes.c_wchar_p("Environment"),
            SMTO_ABORTIFHUNG, 5000, ctypes.byref(result),
        )
    except Exception:
        pass


def status(settings: Settings) -> dict[str, Any]:
    """Report whether the loader is installed and whether it is current."""
    target = settings.custom_directory_file()
    expected = str(settings.runtime_root())
    configured = _read_user_env(ENV_NAME)

    file_ok = False
    file_text = ""
    if target.is_file():
        try:
            file_text = target.read_text(encoding="utf-8", errors="replace")
            file_ok = expected in file_text
        except OSError:
            file_ok = False

    return {
        "envVariable": ENV_NAME,
        "envValue": configured,
        "expectedEnvValue": str(target),
        "envInstalled": configured is not None and Path(configured) == target,
        "customDirectoryFile": str(target),
        "customDirectoryFileExists": target.is_file(),
        "customDirectoryPointsHere": file_ok,
        "pointedAt": file_text.strip().splitlines()[-1] if file_text.strip() else None,
        "packageRuntimeRoot": expected,
        "preservedRoots": _roots_in_custom_directory_file(target) if target.is_file() else [],
        "installed": (configured is not None and Path(configured) == target and file_ok),
    }


def install(settings: Settings) -> dict[str, Any]:
    """Write the custom directory file and set the user-scope variable."""
    previous_env = _read_user_env(ENV_NAME)
    target = write_custom_directory_file(settings)

    if sys.platform != "win32":
        return {
            "installed": False,
            "customDirectoryFile": str(target),
            "reason": "Setting a user-scope environment variable is only automated on Windows.",
            "manualStep": f"export {ENV_NAME}='{target}'",
        }

    persisted = _write_user_env(ENV_NAME, str(target))
    report = status(settings)
    report["customDirectoryFileWritten"] = True
    report["userEnvironmentUpdated"] = persisted
    report["replacedRegistration"] = previous_env
    report["note"] = (
        "Roots from the previous registration were carried over, so other NX "
        "customisations keep working. If the pointer was claimed by another tool, "
        "loading both menus is intentional."
        if report["preservedRoots"]
        else "No previous registration was found to preserve."
    )
    if not persisted:
        report["manualStep"] = f"setx {ENV_NAME} \"{target}\""
    return report


def uninstall(settings: Settings) -> dict[str, Any]:
    """Remove the user-scope variable. The generated file is left in place."""
    removed = _write_user_env(ENV_NAME, None)
    report = status(settings)
    report["userEnvironmentRemoved"] = removed
    return report
